# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ec5ca860066ba69cb0ed2f4e6873b2fad951f068bde80f54b299628abd8a6396fc13714f1cc3ea51a8f31da4738c18e82a6b5856ab5532fb708ba25780412c

test:
  secret_key_base: 764708a123e3a104eb8e19a527d2c2404ac8932be19d3d533c052c68b6f339497a80859f73c2d2729d131bb68a3c2fb096f0715fae5b724f8a25bdeafd6a3875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
